
spring:

  application:
    name: soundy
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:
  liquibase:
logging:
  pattern:
    dateformat:
      MM/dd HH:mm:ss
server:
  port: 4840
