spring:
  application:
    name: soundy
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: 4840
logging:
  pattern:
    dateformat:
      MM/dd HH:mm:ss
