spring:
  application:
    name: soundy
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    user: postgres
    password:
    baseline-on-migrate: true
server:
  port: 4840
logging:
  pattern:
    dateformat:
      HH:mm:ss
  level:
    sql: debug
    web: debug
